import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/appsidebar";
import { Nico_Moji } from "next/font/google";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// const nicoMoji = Nico_Moji({
//   weight: "400", // Adjust weight if needed
//   subsets: ["latin"],
//   variable: "--font-nico-moji",
// });

export const metadata: Metadata = {
  title: "Not Steam",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
      >
        {/* <Navbar /> */}
        <SidebarProvider>
          
          <AppSidebar />
          <SidebarTrigger className="lg:hidden md:hidden"/>
          <main>
            
          </main>
          {children}
        </SidebarProvider>
      </body>
    </html>
  );
}
